RCLONE_REMOTE_SCRIPTS="gdrive:mazterCLOUD/mazter4_2/scripts"
RCLONE_REMOTE_TEXTOS="gdrive:mazterCLOUD/mazter4_2/textos"
RCLONE_REMOTE_GAMELISTS="gdrive:mazterCLOUD/mazter4_2/contenido/gamelists"
RCLONE_REMOTE_PIMAZTERART="gdrive:mazterCLOUD/mazter4_2/contenido/pimazterart"
RCLONE_REMOTE_SUPERPOSICIONES="gdrive:mazterCLOUD/mazter4_2/contenido/superposiciones"
RCLONE_REMOTE_FIXES="gdrive:mazterCLOUD/mazter4_2/fixes"
